services:
  # Backend API Service
  - type: web
    name: hooli-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: VAPI_API_KEY
        sync: false
      - key: VAPI_PHONE_NUMBER_ID
        value: 6a615c7a-c73e-4158-bf64-ffc02dd57192
      - key: VAPI_ASSISTANT_ID
        value: ""
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: hooli-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && REACT_APP_API_URL=$BACKEND_URL npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: hooli-backend
          envVarKey: RENDER_EXTERNAL_URL

